### ISSUE TITLE
Tool dont update until restart

### ISSUE THREAD

**Issue by M4DMAXX** [Gobidev/EDNeutronAssistant#4]
Good Day, today i found out this awesome tool for semi automatic Ploting of my Route.

I got one issue. I plot my route from Sol to Sagittarius A*

I use Neutron Route all seam to work.

But i got Issue: example on start of the tool message appear "Entered Sol/xy" then i plot the route, and fly to the first neutron but it still stay on "Sol/xy"... only when i close and start again i see 2/117 and Message "Entered XY" this happens for me anytime... i have now reach the secound neutron but still on 2/117 and i need to restart tool and then it on 3/117 and say the next system in the list.

How can i fix that? when i always need to restart the tool its not faster then the normal "tab out -> copy & paste" method of Neutron Plotter site.

Thx for any help

**Comment by Gobidev** [comment]
Normally, the program checks once every second, if you have entered a new system and will update even before actually jumping. It looks like there is an issue with this on your machine. What you can do, is opening a command prompt in the folder where your EDNeutronAssistant.exe is located and launching it in verbose mode by supplying it with the -v flag. Here are the stepts for doing so:

1. Open a file explorer and navigate to the folder containing your EDNeutronassistant.exe
2. Open a command prompt in the folder by clicking in the path box, typing `cmd` and pressing enter.
3. Type `.\EDNeutronAssistant.exe -v` to start the program in verbose mode.
4. Open Elite and jump to the next system in your route. The log in the program will contain more information on what it is doing. It should contain the program reading a log every second.
5. Open the folder `C:\Users\YOUR_USERNAME\AppData\Roaming\EDNeutronAssistant\logs`
6. Paste the contents of your latest log file here so I can take a better look at what is wrong.

**Comment by M4DMAXX** [comment]
Thx for your quick Reply. I will do this tomorrow for today i stop after reach 10% of my Route (Daily Goal) ... After i reach the point where only neutron system jumps appear. it work as expected and always update it. maybe it was cause the normal jumps? i look tomorrow

**Comment by Gobidev** [comment]
Ok there could be an issue there, i will look into that at some point. If the problem for you has to do with the normal jump, you could also use the exact route plotter instead of the neutron route plotter, which will calculate in all the normal stars as well.

**Comment by M4DMAXX** [comment]
With exact route plotter it work well. Thx
